default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: omnichannel_inventory_development

test:
  <<: *default
  database: omnichannel_inventory_test

production:
  primary: &primary_production
    <<: *default
    database: omnichannel_inventory_production
    username: omnichannel_inventory
    password: <%= ENV["OMNICHANNEL_INVENTORY_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: omnichannel_inventory_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: omnichannel_inventory_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: omnichannel_inventory_production_cable
    migrations_paths: db/cable_migrate
